title: "The world at dinner"
author: "Laura Bruhn"
email: "laura.bruhn@studio.unibo.it"
description: "This is the website for our project The world at dinner which aims at a better integration of migrants in Europe and a more welcoming environment."

facebook_username: "Peacemakers Project UNIBO"
github_username: "laurapeacemakers"
theme: jekyll-theme-minimal
