title: "The world at dinner"
author: "Laura Bruhn"
email: "laura.bruhn@studio.unibo.it"
description: "This is the website for our project <b>the world at dinner</b> which aims at a better integration of migrants and a more welcoming environment in Europe."

facebook_username: "Peacemakers Project UNIBO"
github_username: "laurapeacemakers"
theme: jekyll-theme-minimal
